// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfJ2PzCkYYM8QkvrF19g54iLF1u10yTB4',
    appId: '1:380795698317:web:a88625d1a78ec17600b6c4',
    messagingSenderId: '380795698317',
    projectId: 'dbflutter-2a2ea',
    authDomain: 'dbflutter-2a2ea.firebaseapp.com',
    storageBucket: 'dbflutter-2a2ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SUK6I0A2Y73BLGBe3-5ytF83cf57r6U',
    appId: '1:380795698317:android:a2348e92b74184f000b6c4',
    messagingSenderId: '380795698317',
    projectId: 'dbflutter-2a2ea',
    storageBucket: 'dbflutter-2a2ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9hV805vo0LoAIgO5iYHME0r054n6wN-I',
    appId: '1:380795698317:ios:cdf4307bad367ac000b6c4',
    messagingSenderId: '380795698317',
    projectId: 'dbflutter-2a2ea',
    storageBucket: 'dbflutter-2a2ea.appspot.com',
    iosClientId: '380795698317-oqtbjce7ljro5ebpp77ndcmi89h99m8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9hV805vo0LoAIgO5iYHME0r054n6wN-I',
    appId: '1:380795698317:ios:cdf4307bad367ac000b6c4',
    messagingSenderId: '380795698317',
    projectId: 'dbflutter-2a2ea',
    storageBucket: 'dbflutter-2a2ea.appspot.com',
    iosClientId: '380795698317-oqtbjce7ljro5ebpp77ndcmi89h99m8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
